name: Fetch APITube News Hourly

on:
  schedule:
    - cron:  '0 * * * *'      # Every hour at minute 0
  workflow_dispatch:         # Manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          APITUBE_API_KEY: ${{ secrets.APITUBE_API_KEY }}
        run: |
          python main.py > output.json
          cat output.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-output
          path: output.json
